import JSZip from 'jszip'
import type { AdBrandKit, AdConcept, AdGenerationRun } from '@/lib/types'
import { downloadAsset } from './storage'

function slugify(s: string): string {
  return (s || 'concept')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40) || 'concept'
}

function csvEscape(value: string): string {
  if (/[",\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`
  return value
}

// Build the export ZIP for the approved concepts of a run (spec §4 step 5):
// README.md + copy.csv + images/ + manifest.json.
export async function buildExportZip(params: {
  run: AdGenerationRun
  brandKit: AdBrandKit | null
  concepts: AdConcept[] // approved only
}): Promise<Buffer> {
  const { run, brandKit, concepts } = params
  const zip = new JSZip()
  const images = zip.folder('images')!

  const manifestConcepts: any[] = []
  const csvRows: string[] = [
    'concept_id,angle,variant_type,headline,primary_text,image_filename',
  ]

  for (const concept of concepts) {
    const filename = `${slugify(concept.angle)}_${concept.variant_type}_${concept.id}.png`

    if (concept.image_url) {
      const png = await downloadAsset(concept.image_url)
      if (png) images.file(filename, png)
    }

    csvRows.push(
      [
        concept.id,
        csvEscape(concept.angle),
        concept.variant_type,
        csvEscape(concept.headline),
        csvEscape(concept.primary_text),
        filename,
      ].join(',')
    )

    manifestConcepts.push({
      concept_id: concept.id,
      angle: concept.angle,
      variant_type: concept.variant_type,
      variant_index: concept.variant_index,
      headline: concept.headline,
      primary_text: concept.primary_text,
      image_filename: filename,
      image_prompt: concept.image_prompt,
      ai_generated: true, // content authenticity flag for v2 Meta publishing
    })
  }

  zip.file('copy.csv', csvRows.join('\n'))

  const manifest = {
    schema_version: 1,
    generated_by: 'Kolrabee Ads Agent v1',
    exported_at: new Date().toISOString(),
    run_id: run.id,
    brand: brandKit
      ? { brand_name: brandKit.brand_name, service_line: brandKit.service_line, target_geo: brandKit.target_geo }
      : null,
    angles: run.synthesized_angles ?? null,
    ai_generated: true,
    concept_count: manifestConcepts.length,
    concepts: manifestConcepts,
  }
  zip.file('manifest.json', JSON.stringify(manifest, null, 2))

  zip.file('README.md', readme(run, brandKit, manifestConcepts.length))

  return zip.generateAsync({ type: 'nodebuffer' }) as unknown as Promise<Buffer>
}

function readme(run: AdGenerationRun, brandKit: AdBrandKit | null, count: number): string {
  return `# ${brandKit?.brand_name ?? 'Ad'} — Creative Package

Generated by **Kolrabee Ads Agent v1** on ${new Date().toISOString()}.
Run ID: \`${run.id}\`

This package contains **${count} approved ad concept${count === 1 ? '' : 's'}** ready for
manual upload to Meta Ads Manager.

> NOTE: All imagery in this package is AI-generated. Disclose AI generation in your
> ad metadata where required, and review against Meta's advertising standards for
> home services before any paid spend.

## Contents

- \`images/\` — one PNG per concept, named \`{angle}_{variant_type}_{concept_id}.png\`
- \`copy.csv\` — headline + primary text per concept (open in Excel / Google Sheets)
- \`manifest.json\` — machine-readable metadata (used by future automated publishing)

## Manual upload steps

1. In Meta Ads Manager, create or open your campaign and ad set.
2. For each row in \`copy.csv\`, create a new ad.
3. Upload the matching image from \`images/\` (filename is in the \`image_filename\` column).
4. Paste the \`headline\` into the Headline field and \`primary_text\` into Primary Text.
5. Set your destination URL and publish (or save as draft for review).

## Naming convention

\`{angle}_{variant_type}_{concept_id}.png\`

- **angle** — the strategic hook (slugified)
- **variant_type** — one of: lifestyle, studio, testimonial_style, before_after
- **concept_id** — the unique Kolrabee concept id (matches \`copy.csv\` and \`manifest.json\`)
`
}
